apiVersion: v1
kind: Namespace
metadata:
  name: grbts
---
apiVersion: v1
kind: Secret
metadata:
  name: license
  namespace: grbts
type: Opaque
stringData:
  gurobi.lic: |
    # /opt/gurobi/gurobi.lic
  fake-grb0.sh: |
    #!/bin/sh
    set -ex
    ip link add grb0 type dummy
    ip link set dev grb0 address 01:23:45:67:ab:cd
    ip link set grb0 up
    ip link show grb0
---
apiVersion: v1
kind: Service
metadata:
  name: grbts
  namespace: grbts
spec:
  type: ClusterIP
  selector:
    app: grbts
  ports:
  - port: 41954
    protocol: TCP
    targetPort: 41954
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grbts
  namespace: grbts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grbts
  template:
    metadata:
      labels:
        app: grbts
    spec:
      hostname: lab0-grb
      hostPID: true
      initContainers:
      - name: lab0-grb-net
        image: registry.access.redhat.com/ubi10/ubi
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        command: ["sh", "/usr/local/sbin/fake-grb0.sh"]
        volumeMounts:
        - name: license
          mountPath: /usr/local/sbin/fake-grb0.sh
          subPath: fake-grb0.sh
      containers:
      - name: grb-ts
        image: ghcr.io/rlinfati/lab0-container:grbts
        resources:
          requests:
            cpu: 50m
            memory: 8Mi
        ports:
        - containerPort: 41954
          protocol: TCP
        volumeMounts:
        - name: license
          mountPath: /opt/gurobi/gurobi.lic
          subPath: gurobi.lic
      volumes:
      - name: license
        secret:
          secretName: license
