apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Secret
metadata:
  name: token
  namespace: cloudflared
stringData:
  token: abcdefghijklmnopqrstuvwxyz1234567890
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      labels:
        pod: cloudflared
    spec:
      containers:
        - image: docker.io/cloudflare/cloudflared:latest
          name: cloudflared
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token
          command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run
