apiVersion: v1
kind: Namespace
metadata:
  name: rbackup
---
apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: rbackup
stringData:
  id_ed25519: |
    # id_ed25519
  rclone.conf: |
    # rclone.conf
