apiVersion: v1
kind: Namespace
metadata:
  name: rbackup
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rbackup-localpath
  namespace: rbackup
spec:
  schedule: "31 07 * * 0,3,5" # minuto hora dia1-31 mes1-12 dia0-6
  timeZone: "America/Santiago"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rbackup
            image: ghcr.io/rlinfati/lab0-container:rbackup
            securityContext:
              privileged: true
            command:
              - /bin/sh
              - -c
              - |
                set -ex
                #
                mkdir -p $HOME/.config/rclone/
                cp /run/rbackup-config/rclone.conf $HOME/.config/rclone/rclone.conf
                #
                rclone version
                #
                rclone sync /home/localpath linfati-rlshared:backup-kubernetes/$K8SNODENAME/ --exclude '**/site-packages/**'
                #
                exec true
            volumeMounts:
            - name: rbackup-config
              mountPath: /run/rbackup-config/
              readOnly: true
            - name: localpath
              mountPath: /home/localpath
            env:
              - name: K8SNODENAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
          volumes:
          - name: rbackup-config
            secret:
              secretName: config
          - name: localpath
            hostPath:
              path: /home/localpath
          restartPolicy: Never
#
# kubectl -n rbackup get all
# kubectl -n rbackup delete cronjob.batch rbackup-localpath
# kubectl -n rbackup logs cronjob.batch/rbackup-localpath
# kubectl -n rbackup create job --from=cronjob/rbackup-localpath rbackup-localpath-$(date '+%Y-%m-%d-%H-%M-%S')
# kubectl -n rbackup delete job --all
