apiVersion: v1
kind: Namespace
metadata:
  name: rbackup
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rbackup-mirror
  namespace: rbackup
spec:
  schedule: "31 03 * * 1" # minuto hora dia1-31 mes1-12 dia0-6
  timeZone: "America/Santiago"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rbackup
            image: ghcr.io/rlinfati/lab0-container:rbackup
            command:
              - /bin/sh
              - -c
              - |
                set -ex
                #
                mkdir -p $HOME/.ssh
                chmod 700 $HOME/.ssh
                cp /run/rbackup-config/id_ed25519 $HOME/.ssh/id_ed25519
                chmod 400 $HOME/.ssh/id_ed25519
                touch $HOME/.ssh/known_hosts
                chmod 600 $HOME/.ssh/known_hosts
                #
                rsync --version
                RSYNCCMD="rsync --delete --delete-after -HPaxi"
                # mirror
                ssh-keyscan -q -t ed25519 cabhs.srv.menoscero.com >> ~/.ssh/known_hosts
                $RSYNCCMD rlinfati@cabhs.srv.menoscero.com:/DataVolume/DataBackup/ /DataVolume/DataBackup/
                exec true
            volumeMounts:
            - name: rbackup-config
              mountPath: /run/rbackup-config/
              readOnly: true
            - name: mirror
              mountPath: /DataVolume/DataBackup
          volumes:
          - name: rbackup-config
            secret:
              secretName: config
          - name: mirror
            hostPath:
              path: /DataVolume/DataBackup
          restartPolicy: Never
#
# find /DataVolume/DataBackup ! -user  root -exec chown 0 {} +
# find /DataVolume/DataBackup ! -group root -exec chgrp 0 {} +
# find /DataVolume/DataBackup -type d ! -perm 0755 -exec chmod 0755 {} +
# find /DataVolume/DataBackup -type f ! -perm 0644 -exec chmod 0644 {} +
# find /DataVolume/DataBackup ! -context 'system_u:object_r:container_file_t:s0' -exec chcon -u system_u -r object_r -t container_file_t -l s0 -- {} +
#
# kubectl -n rbackup get all
# kubectl -n rbackup delete cronjob.batch rbackup-mirror
# kubectl -n rbackup logs cronjob.batch/rbackup-mirror
# kubectl -n rbackup create job --from=cronjob/rbackup-mirror rbackup-mirror-$(date '+%Y-%m-%d-%H-%M-%S')
# kubectl -n rbackup delete job --all
