
apiVersion: v1
kind: Namespace
metadata:
  name: rbackup
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yfinance
  namespace: rbackup
spec:
  storageClassName: localpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rbackup-yfinance
  namespace: rbackup
spec:
  schedule: "31 10,15 * * *" # minuto hora dia1-31 mes1-12 dia0-6
  timeZone: "America/Santiago"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rbackup
            image: ghcr.io/rlinfati/lab0-container:rbackup
            command:
              - /bin/sh
              - -c
              - |
                set -ex
                #
                mkdir -p $HOME/.config/rclone/
                cp /run/rbackup-config/rclone.conf $HOME/.config/rclone/rclone.conf
                #
                rclone version
                #
                cd /opt/yfinance || exit 1
                python3 -m venv /opt/yfinance
                source /opt/yfinance/bin/activate
                pip install --quiet --no-cache-dir yfinance openpyxl matplotlib
                #
                exec python3 script.py
            env:
              - name: K8SNODENAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            volumeMounts:
            - name: rbackup-config
              mountPath: /run/rbackup-config/
              readOnly: true
            - name: yfinance
              mountPath: /opt/yfinance
          volumes:
          - name: rbackup-config
            secret:
              secretName: config
          - name: yfinance
            persistentVolumeClaim:
              claimName: yfinance
          restartPolicy: Never
#
# kubectl -n rbackup get all
# kubectl -n rbackup delete cronjob.batch rbackup-yfinance
# kubectl -n rbackup logs cronjob.batch/rbackup-yfinance
# kubectl -n rbackup create job --from=cronjob/rbackup-yfinance rbackup-yfinance-$(date '+%Y-%m-%d-%H-%M-%S')
# kubectl -n rbackup delete job --all
