apiVersion: batch/v1
kind: CronJob
metadata:
  name: pp-infra
  namespace: prepull
spec:
  schedule: "31 01 * * 4" # minuto hora dia1-31 mes1-12 dia0-6
  timeZone: "America/Santiago"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: pp-rbackup
            image: ghcr.io/rlinfati/lab0-container:rbackup
            command: ["/bin/true"]
            imagePullPolicy: Always
          - name: pp-strongswan
            image: ghcr.io/rlinfati/lab0-container:strongswan
            command: ["/bin/true"]
            imagePullPolicy: Always
          - name: pp-vlmcsd
            image: ghcr.io/rlinfati/lab0-container:vlmcsd
            command: ["/bin/true"]
            imagePullPolicy: Always
          - name: pp-ubi10
            image: registry.access.redhat.com/ubi10/ubi:latest
            command: ["/bin/true"]
            imagePullPolicy: Always
          containers:
          - name: pp-prepull
            image: registry.access.redhat.com/ubi10/ubi:latest
            command: ["/bin/true"]
          restartPolicy: Never
# kubectl -n prepull get all
# kubectl -n prepull create job --from=cronjob/pp-infra pp-infra-$(date '+%Y-%m-%d-%H-%M-%S')
# kubectl -n prepull delete job --all
