# 906-node-ip102.yaml
version: v1alpha1
machine:
    network:
        interfaces:
          - deviceSelector:
              physical: true
            addresses:
              - 192.168.64.102/24
            routes:
              - network: 0.0.0.0/0
                gateway: 192.168.64.1
    time:
        bootTimeout: 5s
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: off
hostname: talos-ip102.home.arpa
