# /etc/strongswan/swanctl/conf.d/ikev2.conf
connections {
    pubkey-eap {
        version = 2
        pools = pool-ipv4
        local {
            auth = pubkey
            certs = le-ikev2-srv.crt
            id = clval.vps.menoscero.com
        }
        remote {
            auth = eap-dynamic
            id = %any
            eap_id = %any
        }
        children {
            tunnel-gwnet {
                local_ts = 10.96.0.0/12, 10.244.0.0/16
                remote_ts = dynamic
                mode = tunnel
            }
        }
    }
}
pools {
    pool-ipv4 {
        addrs = 172.31.101.0/24
        dns = 10.96.0.10
    }
    #pool-ipv6 {
    #    addrs = fd00::172:31:101:0/112
    #}
}
authorities {
    m0-0ca-2024 {
        cacert = m0-0ca-2024.crt
    }
}
#secrets {
#    eap-kubernetes {
#        id = kubernetes
#        secret = "00000000-0000-0000-0000-000000000000"
#    }
#}