apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: strongswan
spec:
  secretName: tls
  dnsNames:
  - server.home.arpa
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  privateKey:
    algorithm: ECDSA
