apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
  namespace: strongswan
spec:
  secretName: tls
  dnsNames:
  - server.home.arpa
  #- grutt.menoscero.com
  #- fenix.ubb.menoscero.com
  issuerRef:
    kind: ClusterIssuer
    name: le-prod
  privateKey:
    algorithm: ECDSA
