apiVersion: v1
kind: Service
metadata:
  name: swan
  namespace: strongswan
  annotations:
    metallb.io/loadBalancerIPs: 146.83.193.155
    metallb.io/allow-shared-ip: 4db62740-043f-4f66-8225-5954828e4bf4
spec:
  type: LoadBalancer
  selector:
    app: swan
  ports:
  - name: isakmp
    port: 500
    protocol: UDP
    targetPort: 500
  - name: nat-t
    port: 4500
    protocol: UDP
    targetPort: 4500
  allocateLoadBalancerNodePorts: false
