apiVersion: v1
kind: Service
metadata:
  name: swan
  namespace: strongswan
spec:
  type: ClusterIP
  selector:
    app: swan
  ports:
  - name: isakmp
    port: 500
    protocol: UDP
    targetPort: 500
  - name: nat-t
    port: 4500
    protocol: UDP
    targetPort: 4500
