apiVersion: v1
kind: Service
metadata:
  name: swan
  namespace: strongswan
  annotations:
    metallb.io/loadBalancerIPs: 1.2.3.4
    metallb.io/allow-shared-ip: 00000000-0000-0000-0000-000000000000
spec:
  type: LoadBalancer
  selector:
    app: swan
  ports:
  - name: isakmp
    port: 500
    protocol: UDP
    targetPort: 500
  - name: nat-t
    port: 4500
    protocol: UDP
    targetPort: 4500
  allocateLoadBalancerNodePorts: false
