apiVersion: apps/v1
kind: Deployment
metadata:
  name: swan
  namespace: strongswan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swan
  template:
    metadata:
      labels:
        app: swan
    spec:
      initContainers:
      - name: cert
        image: docker.io/library/busybox:stable
        command:
        - sh
        - -c
        - |
          awk '/-----BEGIN CERTIFICATE-----/ {n++} {if (n>1) print > "/out/chain.crt"}' /in/tls.crt 
        volumeMounts:
        - name: chain
          mountPath: /out/
        - name: tls
          mountPath: /in/tls.crt
          subPath: tls.crt
      containers:
      - name: swan
        image: ghcr.io/rlinfati/lab0-container:strongswan
        securityContext:
          privileged: true
        ports:
        - name: isakmp
          containerPort: 500
          protocol: UDP
        - name: nat-t
          containerPort: 4500
          protocol: UDP
        volumeMounts:
        - name: ikev2
          mountPath: /etc/strongswan/swanctl/conf.d/ikev2.conf
          subPath: ikev2.conf
        - name: x509ca
          mountPath: /etc/strongswan/swanctl/x509ca/m0-0ca-2024.crt
          subPath: m0-0ca-2024.crt
        - name: chain
          mountPath: /etc/strongswan/swanctl/x509ca/le-ikev2-chain.crt
          subPath: chain.crt
        - name: tls
          mountPath: /etc/strongswan/swanctl/x509/le-ikev2-srv.crt
          subPath: tls.crt
        - name: tls
          mountPath: /etc/strongswan/swanctl/private/le-ikev2-srv.key
          subPath: tls.key
      volumes:
      - name: ikev2
        configMap:
          name: ikev2
      - name: x509ca
        configMap:
          name: x509ca
      - name: tls
        secret:
          secretName: tls
      - name: chain
        emptyDir: {}
