apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: nvidia
handler: nvidia
---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-nvidia
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin
  namespace: kube-nvidia
spec:
  selector:
    matchLabels:
      name: nvidia-device-plugin
  template:
    metadata:
      labels:
        name: nvidia-device-plugin
    spec:
      priorityClassName: "system-node-critical"
      runtimeClassName: nvidia
      containers:
      - image: nvcr.io/nvidia/k8s-device-plugin:v0.18.1
        # FIX: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/k8s-device-plugin/tags
        name: nvidia-device-plugin
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
        env:
          - name: DEVICE_LIST_STRATEGY
            value: "cdi-cri"
        volumeMounts:
        - name: driver-root
          mountPath: /driver-root
          readOnly: true
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: var-run-cdi
          mountPath: /var/run/cdi
      volumes:
      - name: driver-root
        hostPath:
          path: /
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: var-run-cdi
        hostPath:
          path: /var/run/cdi
