apiVersion: v1
kind: Service
metadata:
  name: www
  namespace: jupyterhub
spec:
  selector:
    app: jhub
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: jupyterhub
spec:
  selector:
    app: jhub
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
