apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../20-infra/
  - ../../30-apps/
components:
  - ../common/
patches:
# 20-infra - https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  - target:
      namespace: kube-flannel
      kind: DaemonSet
      name: kube-flannel-ds
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --iface=tailscale0
# 20-infra/700-cloudflare.yaml
  - path: 702-cloudflare-local.yaml
# 20-infra/800-tailscale.yaml
  - path: 802-tailscale-local.yaml
