apiVersion: v1
kind: ServiceAccount
metadata:
  name: localpath
  namespace: localpath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: localpath
  namespace: localpath
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localpath
  namespace: localpath
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: localpath
  namespace: localpath
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: localpath
subjects:
  - kind: ServiceAccount
    name: localpath
    namespace: localpath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: localpath
  namespace: localpath
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: localpath
subjects:
  - kind: ServiceAccount
    name: localpath
    namespace: localpath
