kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: localpath
data:
  config.json: |-
    {
            "nodePathMap":[ {
                    "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths": ["/home/localpath/"]
            } ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0755 -p "$VOL_DIR"
    chown 1000:100 "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: docker.io/library/busybox:stable
