apiVersion: v1
kind: Namespace
metadata:
  name: rbackup
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Secret
metadata:
  name: config
  namespace: rbackup
data:
  id_ed25519:
  rclone.conf:
---
