apiVersion: v1
kind: Service
metadata:
  name: ingress-152lapiz
  namespace: ingress-nginx
  annotations:
    metallb.io/loadBalancerIPs: 146.83.193.152
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  allocateLoadBalancerNodePorts: false
